package com.hibernate.entity;

/**
 * Book generated by MyEclipse Persistence Tools
 */

public class Book implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String id;

	private String title;

	private String author;

	// Constructors

	/** default constructor */
	public Book() {
	}

	/** full constructor */
	public Book(String id, String title, String author) {
		this.id = id;
		this.title = title;
		this.author = author;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

}